# Generated by Django 4.2.3 on 2023-08-11 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblist',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 11, 26, 27, 801455, tzinfo=datetime.timezone.utc), verbose_name='expiration time (of ad)'),
        ),
    ]
