# Generated by Django 4.2.3 on 2023-08-15 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_userprofile_delete_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='joblist',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 14, 9, 41, 35, 48805, tzinfo=datetime.timezone.utc), verbose_name='expiration time (of ad)'),
        ),
    ]
