# Generated by Django 4.2.3 on 2023-08-17 09:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_userprofile_image_alter_joblist_date_and_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='likes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 16, 9, 28, 31, 318780, tzinfo=datetime.timezone.utc), verbose_name='expiration time (of ad)'),
        ),
    ]
